apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: remote-clusters
  namespace: remote-app
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: local-cluster
          operator: NotIn
          values: ["true"]
        - key: feature.open-cluster-management.io/addon-multicluster-global-hub-controller
          operator: In
          values: ["available"]