apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: local-clusters
  namespace: local-app
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          name: "local-cluster"